version: '2'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - TEST_STORAGE_API_TOKEN
      - TEST_STORAGE_API_URL
      - TEST_COMPONENT_ID
      - TEST_COMPONENT_CONFIG_ID
